[package]
name = "gridmind-edge-agent"
version.workspace = true
edition.workspace = true

[dependencies]
gridmind-common = { path = "../common" }
tokio = { workspace = true }
async-nats = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
rusqlite = { workspace = true }
uuid = { workspace = true }
prost = { workspace = true }
bytes = { workspace = true }
