[package]
name = "gridmind-generic-driver"
version.workspace = true
edition.workspace = true

[dependencies]
gridmind-common = { path = "../../common" }
async-trait = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
