[package]
name = "gridmind-modbus-driver"
version.workspace = true
edition.workspace = true

[dependencies]
gridmind-common = { path = "../../common" }
gridmind-generic-driver = { path = "../generic-driver" }
tokio = { workspace = true }
tokio-modbus = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
parking_lot = { workspace = true }
