/**
 * Market Data Library
 * 
 * Reads and processes the parsed market data JSON generated by
 * the download script (scripts/download-market-data.ts).
 * 
 * Used by:
 * - /api/market-data API route
 * - /market page (server component)
 */

import * as fs from 'fs'
import * as path from 'path'

const DATA_FILE = path.join(process.cwd(), 'market', 'data', 'market-data.json')

// Types
export interface HourlyRecord {
  date: string
  hour: number
  period: string
  price: number  // EUR/MWh
  volume: number // MWh
  buyVolume: number
  sellVolume: number
}

export interface DailyStats {
  date: string
  avgPrice: number
  minPrice: number
  maxPrice: number
  avgVolume: number
  totalVolume: number
  peakHourPrice: number
  offPeakAvgPrice: number
  solarHourAvgPrice: number
}

export interface HourlyAverage {
  hour: number
  avgPrice: number
  minPrice: number
  maxPrice: number
  avgVolume: number
  count: number
}

export interface WeeklyStats {
  week: string
  avgPrice: number
  count: number
}

export interface OverallStats {
  avgPrice: number
  minPrice: number
  maxPrice: number
  medianPrice: number
  totalRecords: number
  solarHoursAvg: number
  peakHoursAvg: number
  offPeakAvg: number
  arbitrageSpread: number
}

export interface MarketDataSummary {
  lastUpdated: string
  totalRecords: number
  totalFiles: number
  dateRange: {
    start: string
    end: string
  }
  statistics: {
    overall: OverallStats
    daily: DailyStats[]
    hourlyAvg: HourlyAverage[]
    weekly: WeeklyStats[]
  }
}

export interface MarketDataFull extends MarketDataSummary {
  records: HourlyRecord[]
}

/**
 * Check if market data file exists
 */
export function hasMarketData(): boolean {
  return fs.existsSync(DATA_FILE)
}

/**
 * Get the full market data (including all records)
 */
export function getMarketDataFull(): MarketDataFull | null {
  if (!fs.existsSync(DATA_FILE)) return null
  
  try {
    const raw = fs.readFileSync(DATA_FILE, 'utf-8')
    return JSON.parse(raw) as MarketDataFull
  } catch {
    return null
  }
}

/**
 * Get market data summary (without individual records, for lighter API responses)
 */
export function getMarketDataSummary(): MarketDataSummary | null {
  const data = getMarketDataFull()
  if (!data) return null
  
  // eslint-disable-next-line no-unused-vars
  const { records, ...summary } = data
  return summary
}

/**
 * Get records for a specific date range
 */
export function getRecordsByDateRange(startDate: string, endDate: string): HourlyRecord[] {
  const data = getMarketDataFull()
  if (!data) return []
  
  return data.records.filter(r => r.date >= startDate && r.date <= endDate)
}

/**
 * Get records for a specific date
 */
export function getRecordsByDate(date: string): HourlyRecord[] {
  const data = getMarketDataFull()
  if (!data) return []
  
  return data.records.filter(r => r.date === date)
}

/**
 * Get latest day's records
 */
export function getLatestDayRecords(): { date: string; records: HourlyRecord[] } | null {
  const data = getMarketDataFull()
  if (!data || data.records.length === 0) return null
  
  const latestDate = data.dateRange.end
  const records = data.records.filter(r => r.date === latestDate)
  
  return { date: latestDate, records }
}

/**
 * Get daily stats for last N days
 */
export function getDailyStatsLastNDays(n: number): DailyStats[] {
  const data = getMarketDataFull()
  if (!data) return []
  
  return data.statistics.daily.slice(-n)
}

/**
 * Calculate BESS arbitrage opportunity metrics from market data
 */
export function calculateBESSArbitrage(data: MarketDataSummary): {
  avgDailySpread: number
  avgChargePrice: number   // Avg price during solar hours (charge)
  avgDischargePrice: number // Avg price during peak hours (discharge)
  estimatedRevenuePerMWhPerDay: number
  annualRevenuePerMWh: number
} {
  const stats = data.statistics.overall
  
  const avgChargePrice = stats.solarHoursAvg  // Buy during solar hours (cheap)
  const avgDischargePrice = stats.peakHoursAvg // Sell during peak hours (expensive)
  const avgDailySpread = avgDischargePrice - avgChargePrice
  
  // Revenue per MWh of BESS capacity per cycle
  // Assuming 87.8% round-trip efficiency (Linyang spec)
  const rte = 0.878
  const estimatedRevenuePerMWhPerDay = (avgDischargePrice * rte) - avgChargePrice
  const annualRevenuePerMWh = estimatedRevenuePerMWhPerDay * 365
  
  return {
    avgDailySpread,
    avgChargePrice,
    avgDischargePrice,
    estimatedRevenuePerMWhPerDay,
    annualRevenuePerMWh,
  }
}

/**
 * Generate demo data for when no real data is available
 * 
 * Based on ACTUAL Cyprus Day-Ahead Market data (Oct 2025 onwards):
 * Source: CyprusGrid analysis, Cyprus Mail, Poullikkas (2026) "Challenges of Market Maturity"
 * 
 * Real data points (October 2025 - first month):
 * - Weighted avg MCP: €162.7/MWh
 * - Range: €0 to €500/MWh
 * - 42% of days had midday (11:00-14:00) at/near zero
 * - ~5% of all periods cleared at exactly €0
 * - Night-time avg: ~€163/MWh
 * - Must-run conventional: ~€190/MWh
 * - Max spike: €500/MWh (evening peak)
 * - 86% conventional, 14% renewables
 * 
 * Seasonal adjustments based on Cyprus solar irradiation patterns:
 * - Summer: extreme midday suppression (more solar), higher AC evening demand
 * - Winter: less solar = higher midday prices, shorter duck curve
 */
export function generateDemoData(): MarketDataFull {
  const records: HourlyRecord[] = []
  const startDate = new Date('2025-10-01')
  const endDate = new Date()
  
  // Cyprus DAM hourly price profiles (EUR/MWh) by season
  // Based on actual October 2025 data and seasonal extrapolation
  
  // SUMMER (Jun-Aug): Deep duck curve, extreme solar midday suppression, high AC evening peak
  const summerProfile = [
    110, 100, 90, 85, 80, 75,       // 00:00-05:00 (night - moderate, AC still running)
    60, 40, 20, 8, 3, 0,            // 06:00-11:00 (solar ramp → near-zero)
    0, 0, 5, 25, 80, 150,           // 12:00-17:00 (solar peak → sunset ramp)
    210, 250, 230, 200, 165, 130,   // 18:00-23:00 (evening peak - AC + fossil)
  ]
  
  // WINTER (Nov-Feb): Less solar, higher baseline, shorter duck curve dip
  const winterProfile = [
    140, 130, 120, 115, 110, 115,   // 00:00-05:00 (night - heating demand)
    125, 110, 90, 70, 55, 45,       // 06:00-11:00 (less solar, modest dip)
    40, 45, 55, 80, 120, 170,       // 12:00-17:00 (limited solar, ramp to peak)
    220, 260, 250, 230, 190, 160,   // 18:00-23:00 (evening peak - heating + lighting)
  ]
  
  // SPRING (Mar-May): Transitional, increasing solar
  const springProfile = [
    120, 110, 100, 95, 88, 82,      // 00:00-05:00
    70, 50, 30, 15, 8, 3,           // 06:00-11:00
    2, 5, 15, 40, 75, 140,          // 12:00-17:00
    200, 240, 225, 195, 170, 140,   // 18:00-23:00
  ]
  
  // AUTUMN (Sep-Oct): Transitional, high solar still, matches real Oct data
  const autumnProfile = [
    130, 120, 110, 105, 98, 92,     // 00:00-05:00
    80, 55, 35, 18, 8, 2,           // 06:00-11:00
    0, 3, 15, 45, 85, 155,          // 12:00-17:00
    215, 255, 240, 210, 175, 150,   // 18:00-23:00
  ]
  
  function getSeasonProfile(month: number): number[] {
    if (month >= 5 && month <= 7) return summerProfile    // Jun-Aug (0-indexed: 5,6,7)
    if (month >= 10 || month <= 1) return winterProfile   // Nov-Feb
    if (month >= 2 && month <= 4) return springProfile    // Mar-May
    return autumnProfile                                   // Sep-Oct (8,9)
  }
  
  // Use a seeded random for consistency
  let seed = 42
  function seededRandom(): number {
    seed = (seed * 16807 + 0) % 2147483647
    return (seed - 1) / 2147483646
  }
  
  const currentDate = new Date(startDate)
  while (currentDate <= endDate) {
    const dateStr = currentDate.toISOString().slice(0, 10)
    const dayOfWeek = currentDate.getDay()
    const isWeekend = dayOfWeek === 0 || dayOfWeek === 6
    const month = currentDate.getMonth()
    const profile = getSeasonProfile(month)
    
    // Occasional price spikes (like the €500 event on Oct 6)
    const isSpikeDay = seededRandom() < 0.03 // ~3% of days have a spike event
    
    for (let h = 0; h < 24; h++) {
      const basePrice = profile[h]
      const weekendDiscount = isWeekend ? 0.88 : 1.0
      const randomFactor = 0.82 + seededRandom() * 0.36 // ±18% random variation
      
      // Spike factor for extreme events (evening hours only)
      const spikeFactor = (isSpikeDay && h >= 18 && h <= 21) 
        ? 1.5 + seededRandom() * 1.0  // Up to 2.5x during spike events
        : 1.0
      
      let price = basePrice * weekendDiscount * randomFactor * spikeFactor
      
      // Enforce zero floor and cap at €500 (Cyprus market cap)
      price = Math.max(0, Math.min(500, price))
      
      // More zero-price events during midday solar (42% of days per real data)
      if (h >= 11 && h <= 14 && seededRandom() < 0.42) {
        price = Math.max(0, price * 0.1) // Heavy suppression
      }
      
      const volume = (250 + seededRandom() * 180) * (isWeekend ? 0.82 : 1)
      
      records.push({
        date: dateStr,
        hour: h,
        period: `${String(h).padStart(2, '0')}:00`,
        price: Math.round(price * 100) / 100,
        volume: Math.round(volume * 10) / 10,
        buyVolume: Math.round(volume * 0.52 * 10) / 10,
        sellVolume: Math.round(volume * 0.48 * 10) / 10,
      })
    }
    
    currentDate.setDate(currentDate.getDate() + 1)
  }
  
  // Generate statistics from demo records
  const statistics = computeStatistics(records)
  
  return {
    lastUpdated: new Date().toISOString(),
    totalRecords: records.length,
    totalFiles: 0,
    dateRange: {
      start: startDate.toISOString().slice(0, 10),
      end: endDate.toISOString().slice(0, 10),
    },
    statistics,
    records,
  }
}

function computeStatistics(records: HourlyRecord[]) {
  const prices = records.map(r => r.price).filter(p => p > 0)
  const sortedPrices = [...prices].sort((a, b) => a - b)
  
  const solarPrices = records.filter(r => r.hour >= 6 && r.hour <= 18).map(r => r.price)
  const peakPrices = records.filter(r => r.hour >= 17 && r.hour <= 21).map(r => r.price)
  const offPeakPrices = records.filter(r => r.hour >= 22 || r.hour <= 6).map(r => r.price)
  
  const solarHoursAvg = solarPrices.length > 0 ? solarPrices.reduce((a, b) => a + b, 0) / solarPrices.length : 0
  const peakHoursAvg = peakPrices.length > 0 ? peakPrices.reduce((a, b) => a + b, 0) / peakPrices.length : 0
  const offPeakAvg = offPeakPrices.length > 0 ? offPeakPrices.reduce((a, b) => a + b, 0) / offPeakPrices.length : 0
  
  const overall: OverallStats = {
    avgPrice: prices.reduce((a, b) => a + b, 0) / prices.length,
    minPrice: Math.min(...prices),
    maxPrice: Math.max(...prices),
    medianPrice: sortedPrices[Math.floor(sortedPrices.length / 2)],
    totalRecords: records.length,
    solarHoursAvg,
    peakHoursAvg,
    offPeakAvg,
    arbitrageSpread: peakHoursAvg - solarHoursAvg,
  }
  
  // Daily stats
  const dailyMap = new Map<string, HourlyRecord[]>()
  for (const r of records) {
    if (!dailyMap.has(r.date)) dailyMap.set(r.date, [])
    dailyMap.get(r.date)!.push(r)
  }
  
  const daily: DailyStats[] = []
  for (const [date, dayRecords] of dailyMap) {
    const dp = dayRecords.map(r => r.price)
    const peakR = dayRecords.filter(r => r.hour >= 17 && r.hour <= 21)
    const offPeakR = dayRecords.filter(r => r.hour >= 22 || r.hour <= 6)
    const solarR = dayRecords.filter(r => r.hour >= 6 && r.hour <= 18)
    
    daily.push({
      date,
      avgPrice: dp.reduce((a, b) => a + b, 0) / dp.length,
      minPrice: Math.min(...dp),
      maxPrice: Math.max(...dp),
      avgVolume: dayRecords.reduce((a, r) => a + r.volume, 0) / dayRecords.length,
      totalVolume: dayRecords.reduce((a, r) => a + r.volume, 0),
      peakHourPrice: peakR.length > 0 ? peakR.reduce((a, r) => a + r.price, 0) / peakR.length : 0,
      offPeakAvgPrice: offPeakR.length > 0 ? offPeakR.reduce((a, r) => a + r.price, 0) / offPeakR.length : 0,
      solarHourAvgPrice: solarR.length > 0 ? solarR.reduce((a, r) => a + r.price, 0) / solarR.length : 0,
    })
  }
  daily.sort((a, b) => a.date.localeCompare(b.date))
  
  // Hourly averages
  const hourlyMap = new Map<number, number[]>()
  for (const r of records) {
    if (!hourlyMap.has(r.hour)) hourlyMap.set(r.hour, [])
    hourlyMap.get(r.hour)!.push(r.price)
  }
  
  const hourlyAvg: HourlyAverage[] = []
  for (let h = 0; h < 24; h++) {
    const hp = hourlyMap.get(h) || []
    hourlyAvg.push({
      hour: h,
      avgPrice: hp.length > 0 ? hp.reduce((a, b) => a + b, 0) / hp.length : 0,
      minPrice: hp.length > 0 ? Math.min(...hp) : 0,
      maxPrice: hp.length > 0 ? Math.max(...hp) : 0,
      avgVolume: 0,
      count: hp.length,
    })
  }
  
  // Weekly
  const weeklyMap = new Map<string, number[]>()
  for (const d of daily) {
    const dt = new Date(d.date)
    const day = dt.getDay()
    const diff = dt.getDate() - day + (day === 0 ? -6 : 1)
    dt.setDate(diff)
    const weekStart = dt.toISOString().slice(0, 10)
    if (!weeklyMap.has(weekStart)) weeklyMap.set(weekStart, [])
    weeklyMap.get(weekStart)!.push(d.avgPrice)
  }
  
  const weekly: WeeklyStats[] = Array.from(weeklyMap.entries())
    .map(([week, p]) => ({
      week,
      avgPrice: p.reduce((a, b) => a + b, 0) / p.length,
      count: p.length,
    }))
    .sort((a, b) => a.week.localeCompare(b.week))
  
  return { overall, daily, hourlyAvg, weekly }
}
