/**
 * Market Data Library
 * 
 * Reads and processes the parsed market data JSON generated by
 * the download script (scripts/download-market-data.ts).
 * 
 * Used by:
 * - /api/market-data API route
 * - /market page (server component)
 */

import * as fs from 'fs'
import * as path from 'path'
import { looksLikeEnergyVolume } from '@/lib/market/tsoc-excel-parse'
import {
  computeBessSaturation,
  type BessSaturationResult,
  CYPRUS_GRID,
} from '@/lib/market/cyprus-demand-model'

const DATA_FILE = path.join(process.cwd(), 'market', 'data', 'market-data.json')

// Types
export interface HourlyRecord {
  date: string
  hour: number
  period: string
  price: number  // EUR/MWh
  volume: number // MWh
  buyVolume: number
  sellVolume: number
}

export interface DailyStats {
  date: string
  avgPrice: number
  minPrice: number
  maxPrice: number
  avgVolume: number
  totalVolume: number
  peakHourPrice: number
  offPeakAvgPrice: number
  solarHourAvgPrice: number
}

export interface HourlyAverage {
  hour: number
  avgPrice: number
  minPrice: number
  maxPrice: number
  avgVolume: number
  count: number
}

export interface WeeklyStats {
  week: string
  avgPrice: number
  count: number
}

export interface OverallStats {
  avgPrice: number
  minPrice: number
  maxPrice: number
  /** Date (YYYY-MM-DD) of first half-hourly print at maxPrice in the open-market dataset */
  maxPriceDate?: string
  /** Date (YYYY-MM-DD) of first half-hourly print at minPrice in the open-market dataset */
  minPriceDate?: string
  medianPrice: number
  totalRecords: number
  solarHoursAvg: number
  peakHoursAvg: number
  offPeakAvg: number
  arbitrageSpread: number
}

export interface NewMarketStats {
  avgPrice: number
  minPrice: number
  maxPrice: number
  medianPrice: number
  solarHoursAvg: number
  peakHoursAvg: number
  offPeakAvg: number
  arbitrageSpread: number
  totalDays: number
  zeroPricePeriods: number
}

export interface MarketDataSummary {
  lastUpdated: string
  totalRecords: number
  totalFiles: number
  dateRange: {
    start: string
    end: string
  }
  marketTransition?: string  // Date when open market started (2025-10-01)
  newMarketStats?: NewMarketStats  // Stats for new open market only
  statistics: {
    overall: OverallStats
    daily: DailyStats[]
    hourlyAvg: HourlyAverage[]
    weekly: WeeklyStats[]
  }
}

export interface MarketDataFull extends MarketDataSummary {
  records: HourlyRecord[]
}

/**
 * Check if market data file exists
 */
export function hasMarketData(): boolean {
  return fs.existsSync(DATA_FILE)
}

/**
 * Strip corrupted volume values where parser mistakenly copied price into volume.
 */
export function sanitizeHourlyRecord(record: HourlyRecord): HourlyRecord {
  const volumeOk = looksLikeEnergyVolume(record.volume, record.price)
  const buyOk = record.buyVolume > 0 && looksLikeEnergyVolume(record.buyVolume, record.price)
  return {
    ...record,
    volume: volumeOk ? record.volume : 0,
    buyVolume: buyOk ? record.buyVolume : 0,
    sellVolume:
      record.sellVolume > 0 && looksLikeEnergyVolume(record.sellVolume, record.price)
        ? record.sellVolume
        : 0,
  }
}

/**
 * Get the full market data (including all records)
 */
export function getMarketDataFull(): MarketDataFull | null {
  if (!fs.existsSync(DATA_FILE)) return null
  
  try {
    const raw = fs.readFileSync(DATA_FILE, 'utf-8')
    const data = JSON.parse(raw) as MarketDataFull
    if (data.records?.length) {
      data.records = data.records.map(sanitizeHourlyRecord)
    }
    return data
  } catch {
    return null
  }
}

/**
 * Get market data summary (without individual records, for lighter API responses)
 */
function findOpenMarketPriceExtrema(records: HourlyRecord[]): Pick<OverallStats, 'maxPriceDate' | 'minPriceDate'> {
  if (records.length === 0) return {}

  const sorted = [...records].sort((a, b) => a.date.localeCompare(b.date) || a.hour - b.hour)
  let maxPrice = -Infinity
  let minPrice = Infinity
  let maxPriceDate = ''
  let minPriceDate = ''

  for (const r of sorted) {
    if (r.price > maxPrice) {
      maxPrice = r.price
      maxPriceDate = r.date
    }
    if (r.price < minPrice) {
      minPrice = r.price
      minPriceDate = r.date
    }
  }

  return { maxPriceDate, minPriceDate }
}

export function getMarketDataSummary(): MarketDataSummary | null {
  const data = getMarketDataFull()
  if (!data) return null

  // eslint-disable-next-line no-unused-vars
  const { records, ...summary } = data

  if (!summary.statistics.overall.maxPriceDate && records.length > 0) {
    const extrema = findOpenMarketPriceExtrema(records)
    summary.statistics.overall = { ...summary.statistics.overall, ...extrema }
  }

  return summary
}

/**
 * Get records for a specific date range
 */
export function getRecordsByDateRange(startDate: string, endDate: string): HourlyRecord[] {
  const data = getMarketDataFull()
  if (!data) return []
  
  return data.records.filter(r => r.date >= startDate && r.date <= endDate)
}

/**
 * Get records for a specific date
 */
export function getRecordsByDate(date: string): HourlyRecord[] {
  const data = getMarketDataFull()
  if (!data) return []
  
  return data.records.filter(r => r.date === date)
}

/**
 * Get latest day's records
 */
export function getLatestDayRecords(): { date: string; records: HourlyRecord[] } | null {
  const data = getMarketDataFull()
  if (!data || data.records.length === 0) return null
  
  const latestDate = data.dateRange.end
  const records = data.records.filter(r => r.date === latestDate)
  
  return { date: latestDate, records }
}

/**
 * Get daily stats for last N days
 */
export function getDailyStatsLastNDays(n: number): DailyStats[] {
  const data = getMarketDataFull()
  if (!data) return []
  
  return data.statistics.daily.slice(-n)
}

/**
 * Calculate BESS revenue metrics from market data
 * 
 * ⚠️ REGULATORY NOTE (Feb 2026): BESS cannot buy from the DAM grid in Cyprus yet.
 * Grid arbitrage (buy low / sell high) is NOT legal as of Feb 2026.
 * 
 * COMPLETE DATASET (339 days, Oct 2025 – Sep 2026):
 *   Midday avg (10-14): €104.55/MWh
 *   Peak evening (17-21): €212.42/MWh
 *   Peak-Midday spread: €107.88/MWh
 *   Solar hours avg (06-17): €151.38/MWh
 *   Overall avg MCP: €200.23/MWh
 * 
 * CURRENT revenue model: Curtailment recovery
 *   → Charge cost = €0 (storing otherwise-curtailed solar energy)
 *   → Discharge at peak evening prices (€212/MWh avg)
 *   → Revenue per MWh discharged = €212.42 × 86.32% RTE = €183.40/MWh
 *   → Annual: €167,353 (2.5 MWh/day) to €254,376 (3.8 MWh/day)
 * 
 * FUTURE revenue (when legislation enables BESS market participation):
 *   → Grid arbitrage: buy at midday (€105/MWh), sell at peak (€212/MWh)
 *   → Net: €107.88 spread × 86.32% RTE = €93.12/MWh per cycle
 */
export function calculateBESSArbitrage(data: MarketDataSummary): {
  avgDailySpread: number
  avgChargePrice: number   // Avg price during solar hours (reference)
  avgDischargePrice: number // Avg price during peak hours (discharge value)
  middayAvgPrice: number   // Avg midday price (10-14) — deep solar dip
  estimatedRevenuePerMWhPerDay: number
  annualRevenuePerMWh: number
  // Curtailment recovery metrics (current Cyprus reality)
  curtailmentRevenuePerMWh: number
  curtailmentAnnualPerMWh25: number  // At 25% curtailment
  curtailmentAnnualPerMWh38: number  // At 38% curtailment (Anarita real)
} {
  const stats = data.statistics.overall
  
  const avgChargePrice = stats.solarHoursAvg  // Reference only — BESS cannot buy from grid yet
  const avgDischargePrice = stats.peakHoursAvg // BESS discharge value at peak
  // Use midday price if available (more accurate for BESS charge window)
  const middayAvgPrice = (stats as any).middayAvg || avgChargePrice
  const avgDailySpread = avgDischargePrice - middayAvgPrice
  
  const rte = 0.8632 // 86.32% full system AC-AC RTE incl. cabling
  
  // FUTURE: Grid arbitrage revenue (not yet legal)
  // Buy at midday, sell at peak
  const estimatedRevenuePerMWhPerDay = (avgDischargePrice * rte) - middayAvgPrice
  const annualRevenuePerMWh = estimatedRevenuePerMWhPerDay * 365
  
  // CURRENT: Curtailment recovery revenue
  // Charge cost = €0, discharge at peak price
  const curtailmentRevenuePerMWh = avgDischargePrice * rte // €/MWh discharged
  
  // Annual curtailment recovery for a matched solar+BESS system (e.g. 5MWp + 20MWh)
  // Assumes 1650 kWh/kWp yield, 4:1 solar-to-BESS ratio
  const solarYieldMWhPerMWhBESS = (1650 / 1000) * 4 // MWh solar per MWh BESS per year
  const curtailmentAnnualPerMWh25 = solarYieldMWhPerMWhBESS * 0.25 * rte * avgDischargePrice
  const curtailmentAnnualPerMWh38 = solarYieldMWhPerMWhBESS * 0.38 * rte * avgDischargePrice
  
  return {
    avgDailySpread,
    avgChargePrice,
    avgDischargePrice,
    middayAvgPrice,
    estimatedRevenuePerMWhPerDay,
    annualRevenuePerMWh,
    curtailmentRevenuePerMWh,
    curtailmentAnnualPerMWh25,
    curtailmentAnnualPerMWh38,
  }
}

/**
 * Generate demo data for when no real data is available
 * 
 * Based on ACTUAL Cyprus Day-Ahead Market data (Oct 1, 2025 – Sep 4, 2026):
 * Source: 339 TSOC DAM reports, 62,670 half-hourly records, every trading day
 * Live SSOT: lib/market/cyprus-tsoc-dam-sample.ts
 * 
 * VERIFIED complete dataset:
 * - Overall avg MCP: €200.23/MWh
 * - Midday (10-14):  €104.55/MWh  ← deep in Apr–May; summer 2026 much higher
 * - Solar hours (06-17): €151.38/MWh
 * - Peak evening (17-21): €212.42/MWh
 * - Peak-Midday Spread: €107.88/MWh ← BESS opportunity
 * - Range: €0 to €500/MWh
 */
export function generateDemoData(): MarketDataFull {
  const records: HourlyRecord[] = []
  const startDate = new Date('2025-10-01')
  const endDate = new Date()
  
  // Cyprus DAM hourly price profiles (EUR/MWh) by season
  // UPDATED Feb 2026: Based on ACTUAL TSOC data (21 sample days, Oct 2025 - Feb 2026)
  
  // SUMMER (Jun-Aug): Deeper duck curve, more solar suppression, high AC evening peak
  // Projected from autumn/spring real data with seasonal solar irradiation adjustment
  const summerProfile = [
    155, 150, 145, 140, 138, 135,   // 00:00-05:00 (night - moderate, AC still running)
    130, 110, 85, 60, 40, 20,       // 06:00-11:00 (solar ramp → suppression)
    10, 15, 30, 60, 100, 155,       // 12:00-17:00 (solar peak → sunset ramp)
    185, 200, 195, 188, 175, 162,   // 18:00-23:00 (evening peak - AC + fossil)
  ]
  
  // WINTER (Nov-Feb): REAL DATA from 339-day dataset - deep midday dip even in winter
  const winterProfile = [
    173, 170, 169, 169, 169, 171,   // 00:00-05:00 (night - heating demand)
    174, 174, 167, 146, 102, 80,    // 06:00-11:00 (solar suppresses midday heavily)
    77, 105, 142, 167, 175, 181,    // 12:00-17:00 (trough at noon, ramp to peak)
    185, 186, 183, 179, 176, 174,   // 18:00-23:00 (evening peak)
  ]
  
  // SPRING (Mar-May): Transitional, increasing solar penetration
  const springProfile = [
    158, 153, 148, 145, 142, 140,   // 00:00-05:00
    135, 120, 95, 70, 50, 35,       // 06:00-11:00
    25, 30, 50, 75, 110, 160,       // 12:00-17:00
    188, 198, 195, 190, 178, 165,   // 18:00-23:00
  ]
  
  // AUTUMN (Sep-Oct): REAL DATA - Highest solar suppression, deepest duck curve
  const autumnProfile = [
    165, 160, 155, 152, 150, 148,   // 00:00-05:00
    155, 140, 115, 80, 50, 25,      // 06:00-11:00 (aggressive solar ramp)
    15, 25, 55, 90, 130, 170,       // 12:00-17:00 (near-zero at noon)
    185, 195, 192, 188, 175, 168,   // 18:00-23:00 (evening peak)
  ]
  
  function getSeasonProfile(month: number): number[] {
    if (month >= 5 && month <= 7) return summerProfile    // Jun-Aug (0-indexed: 5,6,7)
    if (month >= 10 || month <= 1) return winterProfile   // Nov-Feb
    if (month >= 2 && month <= 4) return springProfile    // Mar-May
    return autumnProfile                                   // Sep-Oct (8,9)
  }
  
  // Use a seeded random for consistency
  let seed = 42
  function seededRandom(): number {
    seed = (seed * 16807 + 0) % 2147483647
    return (seed - 1) / 2147483646
  }
  
  const currentDate = new Date(startDate)
  while (currentDate <= endDate) {
    const dateStr = currentDate.toISOString().slice(0, 10)
    const dayOfWeek = currentDate.getDay()
    const isWeekend = dayOfWeek === 0 || dayOfWeek === 6
    const month = currentDate.getMonth()
    const profile = getSeasonProfile(month)
    
    // Price spikes do occur (€500 max observed) but are rare in the open market
    const isSpikeDay = seededRandom() < 0.03 // ~3% of days have a price spike
    
    for (let h = 0; h < 24; h++) {
      const basePrice = profile[h]
      const weekendDiscount = isWeekend ? 0.92 : 1.0 // Weekend effect is modest
      const randomFactor = 0.88 + seededRandom() * 0.24 // ±12% random variation (market is less volatile than predicted)
      
      // Spike factor for price events (capped at €500 observed max)
      const spikeFactor = (isSpikeDay && h >= 18 && h <= 21) 
        ? 1.3 + seededRandom() * 0.5  // Up to ~1.8x during spike events
        : 1.0
      
      let price = basePrice * weekendDiscount * randomFactor * spikeFactor
      
      // Enforce zero floor and cap at €500 (observed max in dataset)
      price = Math.max(0, Math.min(500, price))
      
      // Zero-price events during midday solar — 5.2% overall, concentrated 10:00-14:00
      // 29.4% of midday periods have MCP ≤ €50 (real curtailment data)
      if (h >= 10 && h <= 14 && seededRandom() < 0.12) {
        price = Math.max(0, price * 0.08) // Deep solar suppression to near-zero
      }
      
      const volume = (250 + seededRandom() * 180) * (isWeekend ? 0.82 : 1)
      
      records.push({
        date: dateStr,
        hour: h,
        period: `${String(h).padStart(2, '0')}:00`,
        price: Math.round(price * 100) / 100,
        volume: Math.round(volume * 10) / 10,
        buyVolume: Math.round(volume * 0.52 * 10) / 10,
        sellVolume: Math.round(volume * 0.48 * 10) / 10,
      })
    }
    
    currentDate.setDate(currentDate.getDate() + 1)
  }
  
  // Generate statistics from demo records
  const statistics = computeStatistics(records)
  
  return {
    lastUpdated: new Date().toISOString(),
    totalRecords: records.length,
    totalFiles: 0,
    dateRange: {
      start: startDate.toISOString().slice(0, 10),
      end: endDate.toISOString().slice(0, 10),
    },
    statistics,
    records,
  }
}

function computeStatistics(records: HourlyRecord[]) {
  const prices = records.map(r => r.price).filter(p => p > 0)
  const sortedPrices = [...prices].sort((a, b) => a - b)
  
  const solarPrices = records.filter(r => r.hour >= 6 && r.hour <= 18).map(r => r.price)
  const peakPrices = records.filter(r => r.hour >= 17 && r.hour <= 21).map(r => r.price)
  const offPeakPrices = records.filter(r => r.hour >= 22 || r.hour <= 6).map(r => r.price)
  
  const solarHoursAvg = solarPrices.length > 0 ? solarPrices.reduce((a, b) => a + b, 0) / solarPrices.length : 0
  const peakHoursAvg = peakPrices.length > 0 ? peakPrices.reduce((a, b) => a + b, 0) / peakPrices.length : 0
  const offPeakAvg = offPeakPrices.length > 0 ? offPeakPrices.reduce((a, b) => a + b, 0) / offPeakPrices.length : 0
  
  const { maxPriceDate, minPriceDate } = findOpenMarketPriceExtrema(records)

  const overall: OverallStats = {
    avgPrice: prices.reduce((a, b) => a + b, 0) / prices.length,
    minPrice: Math.min(...prices),
    maxPrice: Math.max(...prices),
    maxPriceDate,
    minPriceDate,
    medianPrice: sortedPrices[Math.floor(sortedPrices.length / 2)],
    totalRecords: records.length,
    solarHoursAvg,
    peakHoursAvg,
    offPeakAvg,
    arbitrageSpread: peakHoursAvg - solarHoursAvg,
  }
  
  // Daily stats
  const dailyMap = new Map<string, HourlyRecord[]>()
  for (const r of records) {
    if (!dailyMap.has(r.date)) dailyMap.set(r.date, [])
    dailyMap.get(r.date)!.push(r)
  }
  
  const daily: DailyStats[] = []
  for (const [date, dayRecords] of dailyMap) {
    const dp = dayRecords.map(r => r.price)
    const peakR = dayRecords.filter(r => r.hour >= 17 && r.hour <= 21)
    const offPeakR = dayRecords.filter(r => r.hour >= 22 || r.hour <= 6)
    const solarR = dayRecords.filter(r => r.hour >= 6 && r.hour <= 18)
    
    daily.push({
      date,
      avgPrice: dp.reduce((a, b) => a + b, 0) / dp.length,
      minPrice: Math.min(...dp),
      maxPrice: Math.max(...dp),
      avgVolume: dayRecords.reduce((a, r) => a + r.volume, 0) / dayRecords.length,
      totalVolume: dayRecords.reduce((a, r) => a + r.volume, 0),
      peakHourPrice: peakR.length > 0 ? peakR.reduce((a, r) => a + r.price, 0) / peakR.length : 0,
      offPeakAvgPrice: offPeakR.length > 0 ? offPeakR.reduce((a, r) => a + r.price, 0) / offPeakR.length : 0,
      solarHourAvgPrice: solarR.length > 0 ? solarR.reduce((a, r) => a + r.price, 0) / solarR.length : 0,
    })
  }
  daily.sort((a, b) => a.date.localeCompare(b.date))
  
  // Hourly averages
  const hourlyMap = new Map<number, number[]>()
  for (const r of records) {
    if (!hourlyMap.has(r.hour)) hourlyMap.set(r.hour, [])
    hourlyMap.get(r.hour)!.push(r.price)
  }
  
  const hourlyAvg: HourlyAverage[] = []
  for (let h = 0; h < 24; h++) {
    const hp = hourlyMap.get(h) || []
    hourlyAvg.push({
      hour: h,
      avgPrice: hp.length > 0 ? hp.reduce((a, b) => a + b, 0) / hp.length : 0,
      minPrice: hp.length > 0 ? Math.min(...hp) : 0,
      maxPrice: hp.length > 0 ? Math.max(...hp) : 0,
      avgVolume: 0,
      count: hp.length,
    })
  }
  
  // Weekly
  const weeklyMap = new Map<string, number[]>()
  for (const d of daily) {
    const dt = new Date(d.date)
    const day = dt.getDay()
    const diff = dt.getDate() - day + (day === 0 ? -6 : 1)
    dt.setDate(diff)
    const weekStart = dt.toISOString().slice(0, 10)
    if (!weeklyMap.has(weekStart)) weeklyMap.set(weekStart, [])
    weeklyMap.get(weekStart)!.push(d.avgPrice)
  }
  
  const weekly: WeeklyStats[] = Array.from(weeklyMap.entries())
    .map(([week, p]) => ({
      week,
      avgPrice: p.reduce((a, b) => a + b, 0) / p.length,
      count: p.length,
    }))
    .sort((a, b) => a.week.localeCompare(b.week))
  
  return { overall, daily, hourlyAvg, weekly }
}

/** BESS market saturation vs modeled 16h addressable demand (must-run deducted). */
export function getBessSaturation() {
  return computeBessSaturation()
}

export {
  computeBessSaturation,
  type BessSaturationResult,
  CYPRUS_GRID,
} from '@/lib/market/cyprus-demand-model'
